### ISSUE TITLE
typo in services.md

### ISSUE THREAD

**Issue by jmazzitelli** [mhausenblas/kbe#2]
Was reading this: http://kubernetesbyexample.com/services/

And found a typo in the command:

```
$ kubectl gkubectl get pods -l app=sise
```

Notice the "gkubectl" - that shouldn't be there.

Looks like this is line 112 here: https://github.com/mhausenblas/kbe/blame/master/content/page/services.md#L112

**Comment by mhausenblas** [comment]
Thank you, fixed!
